# =========================
# 1. Build stage
# =========================

FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN DIRECT_URL="dummy" npx prisma generate

RUN npm run build


# =========================
# 2. Production stage
# =========================

FROM node:24-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY --from=build /app/dist ./dist
COPY --from=build /app/src/generated/libquery_engine-* ./dist/generated/
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/prisma.config.ts ./prisma.config.ts

EXPOSE 5001

CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]
