import { PrismaClient } from "./../../src/generated/client";

export async function seedItems(
  prisma: PrismaClient,
  users: any[],
  categories: any[],
  colors: any[],
) {
  const itemData = [
    {
      user: 1,
      type: "LOST" as const,
      title: "Black MacBook Air",
      description: "Black MacBook Air with a small sticker.",
      category: 0,
      location: "Main Library",
      color: 0,
      date: "2026-09-01",
      status: "OPEN" as const,
    },
    {
      user: 2,
      type: "LOST" as const,
      title: "Student ID Card",
      description: "Student ID card with blue holder.",
      category: 1,
      location: "Building A",
      color: 3,
      date: "2026-09-02",
      status: "OPEN" as const,
    },
    {
      user: 3,
      type: "LOST" as const,
      title: "Black Backpack",
      description: "Large black backpack containing books.",
      category: 3,
      location: "Cafeteria",
      color: 0,
      date: "2026-09-03",
      status: "RESOLVED" as const,
    },
    {
      user: 4,
      type: "LOST" as const,
      title: "Car Keys",
      description: "Car keys with a red keychain.",
      category: 5,
      location: "Parking Area",
      color: 2,
      date: "2026-09-04",
      status: "OPEN" as const,
    },
    {
      user: 5,
      type: "LOST" as const,
      title: "Brown Wallet",
      description: "Brown leather wallet.",
      category: 7,
      location: "Student Center",
      color: 7,
      date: "2026-09-05",
      status: "OPEN" as const,
    },
    {
      user: 6,
      type: "LOST" as const,
      title: "White Shirt",
      description: "White long sleeve shirt.",
      category: 2,
      location: "Classroom 201",
      color: 1,
      date: "2026-09-06",
      status: "RESOLVED" as const,
    },
    {
      user: 7,
      type: "LOST" as const,
      title: "Programming Book",
      description: "JavaScript programming book.",
      category: 6,
      location: "Computer Lab",
      color: 3,
      date: "2026-09-07",
      status: "OPEN" as const,
    },
    {
      user: 8,
      type: "LOST" as const,
      title: "Silver Necklace",
      description: "Silver necklace with round pendant.",
      category: 8,
      location: "Gym",
      color: 6,
      date: "2026-09-08",
      status: "OPEN" as const,
    },
    {
      user: 9,
      type: "LOST" as const,
      title: "Pink Earbuds Case",
      description: "Pink wireless earbuds case.",
      category: 0,
      location: "Lecture Hall",
      color: 8,
      date: "2026-09-09",
      status: "RESOLVED" as const,
    },
    {
      user: 1,
      type: "LOST" as const,
      title: "Green Notebook",
      description: "Green notebook with university logo.",
      category: 6,
      location: "Library",
      color: 4,
      date: "2026-09-10",
      status: "OPEN" as const,
    },

    {
      user: 2,
      type: "FOUND" as const,
      title: "Blue Wallet",
      description: "Blue wallet found near cafeteria.",
      category: 7,
      location: "Cafeteria",
      color: 3,
      date: "2026-09-05",
      status: "OPEN" as const,
    },
    {
      user: 3,
      type: "FOUND" as const,
      title: "Black Smartphone",
      description: "Black smartphone found on classroom desk.",
      category: 0,
      location: "Classroom 105",
      color: 0,
      date: "2026-09-06",
      status: "OPEN" as const,
    },
    {
      user: 4,
      type: "FOUND" as const,
      title: "Red Backpack",
      description: "Red backpack found outside library.",
      category: 3,
      location: "Library Entrance",
      color: 2,
      date: "2026-09-07",
      status: "RESOLVED" as const,
    },
    {
      user: 5,
      type: "FOUND" as const,
      title: "White USB Drive",
      description: "Small white USB drive.",
      category: 0,
      location: "Computer Lab",
      color: 1,
      date: "2026-09-08",
      status: "OPEN" as const,
    },
    {
      user: 6,
      type: "FOUND" as const,
      title: "Yellow Notebook",
      description: "Yellow notebook found in study room.",
      category: 6,
      location: "Study Room",
      color: 5,
      date: "2026-09-09",
      status: "OPEN" as const,
    },
    {
      user: 7,
      type: "FOUND" as const,
      title: "Black Keys",
      description: "Keys attached to black keychain.",
      category: 5,
      location: "Main Entrance",
      color: 0,
      date: "2026-09-10",
      status: "OPEN" as const,
    },
    {
      user: 8,
      type: "FOUND" as const,
      title: "Brown Leather Bag",
      description: "Small brown leather shoulder bag.",
      category: 3,
      location: "Parking Area",
      color: 7,
      date: "2026-09-11",
      status: "RESOLVED" as const,
    },
    {
      user: 9,
      type: "FOUND" as const,
      title: "Pink Bracelet",
      description: "Pink bracelet with decorative stones.",
      category: 8,
      location: "Gym",
      color: 8,
      date: "2026-09-12",
      status: "OPEN" as const,
    },
    {
      user: 1,
      type: "FOUND" as const,
      title: "Gray Hoodie",
      description: "Gray hoodie found in lecture hall.",
      category: 2,
      location: "Lecture Hall",
      color: 6,
      date: "2026-09-13",
      status: "OPEN" as const,
    },
    {
      user: 2,
      type: "FOUND" as const,
      title: "Blue Card Holder",
      description: "Blue student card holder.",
      category: 1,
      location: "Student Center",
      color: 3,
      date: "2026-09-14",
      status: "RESOLVED" as const,
    },
  ];

  const items = [];

  for (const data of itemData) {
    const user = users[data.user];
    const category = categories[data.category];
    const color = colors[data.color];

    const item = await prisma.item.create({
      data: {
        userId: user.id,
        type: data.type,
        title: data.title,
        description: data.description,
        categoryId: category.id,
        location: data.location,
        colorId: color.id,
        dateLostOrFound: new Date(data.date),
        status: data.status,
        createdById: user.id,
        updatedById: user.id,
      },
    });

    items.push(item);
  }

  console.log("✅ Items seeded: 20");

  return items;
}
